In [1]:
#To supress warnings in the output
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:

df = pd.read_csv("Data_for_UCI_named.csv")
df.head()


tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
df.describe()

tau1          tau2          tau3          tau4            p1  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       5.250000      5.250001      5.250004      5.249997      3.750000   
std        2.742548      2.742549      2.742549      2.742556      0.752160   
min        0.500793      0.500141      0.500788      0.500473      1.582590   
25%        2.874892      2.875140      2.875522      2.874950      3.218300   
50%        5.250004      5.249981      5.249979      5.249734      3.751025   
75%        7.624690      7.624893      7.624948      7.624838      4.282420   
max        9.999469      9.999837      9.999450      9.999443      5.864418   

                 p2            p3            p4            g1            g2  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -1.250000     -1.250000     -1.250000      0.525000      0.525000   
std        0.433035      0.433035      0.433035      0.274256      0.274255   
min       -1.999891     -1.999945     -1.999926      0.050009      0.050053   
25%       -1.624901     -1.625025     -1.624960      0.287521      0.287552   
50%       -1.249966     -1.249974     -1.250007      0.525009      0.525003   
75%       -0.874977     -0.875043     -0.875065      0.762435      0.762490   
max       -0.500108     -0.500072     -0.500025      0.999937      0.999944   

                 g3            g4          stab  
count  10000.000000  10000.000000  10000.000000  
mean       0.525000      0.525000      0.015731  
std        0.274255      0.274255      0.036919  
min        0.050054      0.050028     -0.080760  
25%        0.287514      0.287494     -0.015557  
50%        0.525015      0.525002      0.017142  
75%        0.762440      0.762433      0.044878  
max        0.999982      0.999930      0.109403

In [5]:
df.shape


(10000, 14)

In [6]:
df.info


<bound method DataFrame.info of           tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1       

In [7]:
#dropping stab column as its related with stabf
df=df.drop('stab',axis=1)
df.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4', 'stabf'],
      dtype='object')

In [8]:
#checking for missing values
df.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stabf    0
dtype: int64

That means no null value

In [9]:

# data split

from sklearn.model_selection import train_test_split

X_data=df.drop('stabf', axis=1)
Y_data=df[['stabf']]

x_train, x_test, y_train,y_test = train_test_split(X_data, Y_data, test_size=0.2, random_state=1)

In [10]:
#standard scaler

from sklearn.preprocessing import StandardScaler
myscaler=StandardScaler()
Xt_Scaled=pd.DataFrame(myscaler.fit_transform(x_train), columns=x_train.columns)
Xtest_Scaled=pd.DataFrame(myscaler.transform(x_test), columns=x_test.columns)

# Xt_Scaled.columns=x_train.columns
# Xtest_Scaled.columns=x_test.columns

print(Xt_Scaled.head())
print(Xtest_Scaled.head())
# y_train=y_train.reset_index(drop=True)
# y_test=y_test.reset_index(drop=True)
# y_train

       tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.367327 -0.986042  0.650447  1.547527 -0.291490  0.061535  1.293862   
1 -0.064659  0.089437  1.035079 -1.641494  0.619865 -0.067235 -1.502925   
2 -1.467850  1.298418 -0.502536  1.166046 -0.180521  0.490603  0.682560   
3  0.820081  0.529920  1.299657 -1.141975 -0.812854 -0.763632  1.521579   
4  0.665424 -1.425627  0.312300  0.919137 -1.614296  0.760315  1.422019   

         p4        g1        g2        g3        g4  
0 -0.845074  0.160918  0.339859  0.585568  0.492239  
1  0.486613 -0.293143 -1.558488  1.429649 -1.443521  
2 -0.855302  1.399350  1.451534 -1.045743  0.492489  
3  0.658780 -0.958319  1.361958  1.604140  0.275303  
4  0.639243  1.676895  0.695660  1.137504 -1.312575  
       tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.593951 -0.412733  1.503924  1.116943  0.403423 -1.492971 -0.785033   
1  0.202190  0.374416 -0.188800 -0.522268 -0.225967 -1.058483  0.420047   


In [11]:
type(x_train)

pandas.core.frame.DataFrame

In [12]:
#label encoding for the categorical data of column 'stabf'
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_train =pd.DataFrame(encoder.fit_transform(y_train.reset_index(drop=True)), columns=y_train.columns)
y_test = pd.DataFrame(encoder.transform(y_test.reset_index(drop=True)),columns=y_test.columns) 

In [13]:
def score_data(y_test,pred_y, clf):
  print('\n\n'+clf)
  print("\n CONFUSION MATRIX \n", confusion_matrix(y_test,pred_y))
  print(classification_report(y_test,pred_y))
  print("Accuracy Score is: ", accuracy_score(y_test, pred_y))

In [14]:
#Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
Rf=RandomForestClassifier(n_estimators=100, random_state=1)
Rf.fit(Xt_Scaled,y_train)
pred_y=pd.Series(Rf.predict(Xtest_Scaled))
pred_y.value_counts()

1    1320
0     680
dtype: int64

In [15]:
#Checking the accuracy, confusion matrix etc for Random Forest Classifier

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
score_data(y_test, pred_y,'RandomForest Classifier')



RandomForest Classifier

 CONFUSION MATRIX 
 [[ 625   87]
 [  55 1233]]
              precision    recall  f1-score   support

           0       0.92      0.88      0.90       712
           1       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy Score is:  0.929


In [16]:
#XGB Classifier

from xgboost import XGBClassifier
clf=XGBClassifier()
clf.fit(Xt_Scaled,y_train)
pred_y=clf.predict(Xtest_Scaled)
score_data(y_test, pred_y,'XGBClassifier')



XGBClassifier

 CONFUSION MATRIX 
 [[ 648   64]
 [  45 1243]]
              precision    recall  f1-score   support

           0       0.94      0.91      0.92       712
           1       0.95      0.97      0.96      1288

    accuracy                           0.95      2000
   macro avg       0.94      0.94      0.94      2000
weighted avg       0.95      0.95      0.95      2000

Accuracy Score is:  0.9455


In [17]:
#LGBM Classifier

from lightgbm import LGBMClassifier
clf= LGBMClassifier()
clf.fit(Xt_Scaled,y_train)
pred_y=clf.predict(Xtest_Scaled)
score_data(y_test, pred_y,'LGBM')



LGBM

 CONFUSION MATRIX 
 [[ 641   71]
 [  50 1238]]
              precision    recall  f1-score   support

           0       0.93      0.90      0.91       712
           1       0.95      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.94      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000

Accuracy Score is:  0.9395


In [18]:
#ExtraTreesClassifier

from sklearn.ensemble import ExtraTreesClassifier
ext_clf=ExtraTreesClassifier()
ext_clf.fit(Xt_Scaled,y_train)
pred_y=ext_clf.predict(Xtest_Scaled)
score_data(y_test, pred_y, 'ExtraTreesClassifier Initially')



ExtraTreesClassifier Initially

 CONFUSION MATRIX 
 [[ 604  108]
 [  37 1251]]
              precision    recall  f1-score   support

           0       0.94      0.85      0.89       712
           1       0.92      0.97      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy Score is:  0.9275


In [19]:
#HyperTuning ExtraTreesClassifier

n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None] 
hyperparameter_grid = {'n_estimators': n_estimators,'min_samples_leaf': min_samples_leaf,'min_samples_split': min_samples_split,'max_features': max_features}
from sklearn.model_selection import RandomizedSearchCV
etc_clf=ExtraTreesClassifier()
rdm = RandomizedSearchCV(etc_clf, param_distributions = hyperparameter_grid, cv=5, n_iter=10, n_jobs=-1, verbose=1, random_state=1, scoring='accuracy')
rdm.fit(Xt_Scaled, y_train)
rdm.best_params_

Fitting 5 folds for each of 10 candidates, totalling 50 fits


{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 8,
 'max_features': None}

In [20]:
etc_clf_opt=ExtraTreesClassifier(max_features=None,min_samples_leaf=8,min_samples_split=2, n_estimators=1000)
etc_clf_opt.fit(Xt_Scaled, y_train)
pred_y=etc_clf_opt.predict(Xtest_Scaled)
score_data(y_test, pred_y, clf='ExtraTreesClassifier Optimal')



ExtraTreesClassifier Optimal

 CONFUSION MATRIX 
 [[ 618   94]
 [  53 1235]]
              precision    recall  f1-score   support

           0       0.92      0.87      0.89       712
           1       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy Score is:  0.9265


The Accuracy for Optimal ExtraTrees Classifier is 0.9285, whereas for Untuned ExtratreesClassifier is 0.931
<br>Thus, Optimal Model has lower accuracy than the initial model

---



In [21]:
#Feature Importances for Optimal Model of ExtraTreesClassifier
feature_imp=etc_clf_opt.feature_importances_

xyz=pd.DataFrame(feature_imp, index=Xt_Scaled.columns, columns=['Importance'])
print("Max Importance is of: ", xyz[['Importance']].idxmax())
print("Min Importance is of: ", xyz[['Importance']].idxmin())


Max Importance is of:  Importance    tau2
dtype: object
Min Importance is of:  Importance    p1
dtype: object
